// Copyright 2024 The Reallusion Authors. All Rights Reserved.
#define PLUGIN_NAME "CC_ControlRig"
#define CONTENT_BROWSERT_CONTEXT_MENU_RIG_SETUP_SECTION_NAME "CC RIGS"
#define CONTENT_BROWSERT_CONTEXT_MENU_RIG_SETUP_ACTION_NAME "Create CC Control Rig"
#define CONTENT_BROWSERT_CONTEXT_MENU_RIG_SETUP_ACTION_TOOLTIP "Add UE Control Rig to CC Characters"
#define NO_SELECTED_ACTORS_RIG_SETUP_MESSAGE "Failed to issue command. Please select a skeletal mesh actor."
#define SELECTED_ACTORS_RIG_SETUP_FINISHED_MESSAGE "The CC Rigs is complete."
#define LIVE_LINK_SKELETON_BEGIN_RIG_SETUP_MESSAGE  "iClone Live Link function will be unavailable after a CC Control Rig is applied.\
                                                     You can re-enable iClone Live Link in the Actor Detail window."
#define LIVE_LINK_SKELETON_NOTCOMPATIBLE_MESSAGE   "This skeleton structure is not supported."

#define RL_LIVE_LINK_BLUEPRINT_SUFFIX "_Blueprint"
#define RL_LIVE_LINK_ANIMATION_BLUEPRINT_SUFFIX "_AnimationBlueprint"

#define UNREAL_ASSET_FORMAT ".uasset"
#define RIG_SETUP_FOLDER_PATH "/Rigs"
#define RIG_SETUP_FOLDER_SHARE_CONTENT_PATH "/CC_Rigs"
#define RIG_SETUP_FOLDER_SHARE_PICKER_FOLDER_PATH "/CC_Rigs/Picker_Assets"
#define RIG_SETUP_FOLDER_SHARE_CONTENT_CONTROL_PATH "/CC_Rigs/Controls"
#define RIG_SETUP_CONTENT_PATH "/CC_ControlRig/Content"
#define RIG_SETUP_CONTENT_UTILITY_PATH "/Content/Utility"
#define RIG_SETUP_CONTENT_PICKER_FOLDER_PATH "/Content/Utility/Picker_Assets"
#define RIG_SETUP_CONTENT_PICKER_FOLDER "Picker_Assets"
#define RIG_SETUP_CONTENT_5_3_PICKER_FOLDER "/Content/Utility/Picker5_3"
#define RIG_SETUP_CONTENT_5_4_PICKER_FOLDER "/Content/Utility/Picker5_4"
#define RIG_SETUP_FACE_ANIMATION_BLUEPRINT_TEMPLATE_NAME "CC_FaceRig_AB"
#define RIG_SETUP_BODY_ANIMATION_BLUEPRINT_TEMPLATE_NAME "CC_BodyRig_AB"
#define RIG_SETUP_BODY_WITH_LIVE_LINK_ANIMATION_BLUEPRINT_TEMPLATE_NAME "CC_Rig_With_LiveLink_AB"
#define RIG_SETUP_BLUEPRINT_TEMPLATE_NAME "CC_Rig_BP"
#define RIG_SETUP_WITH_LIVE_LINK_BLUEPRINT_TEMPLATE_NAME "CC_Rig_With_LiveLink_BP"
#define RIG_SETUP_FACE_RIG_TEMPLATE_NAME  "CC_Face_Rig"
#define RIG_SETUP_BODY_RIG_TEMPLATE_NAME  "CC_Body_Rig"
#define RIG_SETUP_BP_WITH_LIVE_LINK_CODE "RigLiveLinkCode_Character_BP"
#define RIG_SETUP_AB_WITH_LIVE_LINK_CODE "RigLiveLinkCode_Charataer_AB"

#define CC_HEAD "head"
#define CC_FACIAL "cc_base_facialbone"
#define CC_JAW_ROOT "cc_base_jawroot"
#define CC_UPPER_JAW "cc_base_upper_jaw"
#define CC_TEETH_01 "cc_base_teeth01"
#define CC_TEETH_02 "cc_base_teeth02"
#define CC_TONGUE_01 "cc_base_tongue01"
#define CC_TONGUE_02 "cc_base_tongue02"
#define CC_TONGUE_03 "cc_base_tongue03"
#define CC_LEFT_EYE "cc_base_l_eye"
#define CC_RIGHT_EYE "cc_base_r_eye"
